// Code generated by Arduino IoT Cloud
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// header file with arduino iot cloud variables
#include "espSecret.h"

void onColorChange();

String color;

void initProperties()
{
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(color, READWRITE, ON_CHANGE, onColorChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
